application.data-dir: ${DATA_DIR:uploads}
server.port: 8081
spring.mail:
  protocol: smtp
  host: smtp.gmail.com
  port: 587
  username: arsytamawisa@gmail.com
  password: meaickkuvnjpyaod
  properties.mail.smtp:
    auth: true
    starttls.enable: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reimburse
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  messages.basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
